### ISSUE TITLE
Assistants aren't assigned a table / status stays "open"

### ISSUE THREAD

**Issue by Corborax** [eurofurence/dealer-registration#25]
There are several issues at once.

- Assistants aren't assigned automatically the table number of their parent.

- Assistants do not automatically copy the Application Status of their parent (-> Table Accepted). 

--- Idea: They should have their own Status "Assigned Assistant" 

-

**Comment by Fenrikur** [comment]
The status actually isn't an actual property stored in the database, but rather derived from various other columns/attributes of the model.
@julsteele: We might want to consider whether Assistants, instead of explicitly having the table number set on them by a side-effect, should just implicitly inherit it via their parent relationship with the Dealer.

**Comment by julsteele** [comment]
Sounds good. That could also be used for the status calculation (since not every status makes sense for an assistant).
